export const inTheaters = state => state.inTheaters
export const inTheatersList = state => state.inTheatersList
export const detail = state => state.detail
export const comming = state => state.comming
export const commingList = state => state.commingList
export const weekly = state => state.weekly
export const top = state => state.top
export const topList = state => state.topList
export const showLoading = state => state.showLoading
