export const GET_IN_THEATERS = 'GET_IN_THEATERS'
export const GET_DETAIL = 'GET_DETAIL'
export const TOOGLE_LOADING = 'TOOGLE_LOADING'
export const GET_COMMING = 'GET_COMMING'
export const GET_WEEKLY = 'GET_WEEKLY'
export const GET_TOP = 'GET_TOP'
